# -*- coding: utf-8 -*-
"""5.Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utZf-1FqYY2TBcF9QScM45TWP472YFyC
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import os

#from google.colab import data_table
#data_table.enable_dataframe_formatter()

from google.colab import data_table
data_table.disable_dataframe_formatter()

# unbegrenzte Zeilen und Spalten anzeigen
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

# Google Drive mounten
drive.mount('/content/drive')

# Zielordner definieren
folder_path = '/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks'
os.makedirs(folder_path, exist_ok=True)  # Ordner erstellen, falls nicht vorhanden

# Import Train and Test Data.
loan_data_inputs_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_train.csv', index_col = 0)
loan_data_targets_train = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_train.csv', index_col = 0,)
loan_data_inputs_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_inputs_test.csv', index_col = 0)
loan_data_targets_test = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_targets_test.csv', index_col = 0, header = None)

loan_data_targets_train.head()

loan_data_backup = pd.read_csv('/content/drive/MyDrive/Lending-Club-Credit-Scoring/notebooks/loan_data_2015.csv')

loan_data_backup.shape

loan_data = loan_data_backup.copy()

loan_data.head()

loan_data.info()

"""# Population Stability Index: Preprocessing

### >>> The code from here to the other line starting with '>>>' is copied from the Data Preparation notebook, with minor adjustments. We have to perform the exact same data preprocessing, fine-classing, and coarse classing on the new data, in order to be able to calculate statistics for the exact same variables to the ones we used for training and testing the PD model.

### Preprocessing few continuous variables

## General Preprocessing
"""

loan_data['emp_length'].unique()

# Ersetzt den String '10+ years' durch '10', um eine numerische Konvertierung zu ermöglichen.
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('10+ years', '10', regex=False)
# Ersetzt '< 1 year' durch '0', da dies einem Jahrzehnt von 0 Jahren entspricht.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0), regex=False)
# Ersetzt 'n/a' (Not Applicable) durch '0', da fehlende Werte hier als 0 Jahre betrachtet werden.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0), regex=False)
# Entfernt den String ' years' aus den Werten, um nur die numerischen Anteile zu behalten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '', regex=False)
# Entfernt den String ' year' (Singular) aus den Werten.
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '', regex=False)

type(loan_data['emp_length_int'][0])

loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'], errors='coerce')

loan_data['emp_length_int'].head()

loan_data['emp_length_int'].dtype

type(loan_data['emp_length_int'][0])

"""Earliest credit line"""

loan_data['earliest_cr_line'].head()

# Konvertiert die Spalte 'earliest_cr_line' in ein Datumsformat. Das Format '%b-%y' gibt an, dass das Datum im Format 'Monat-Jahr' (z.B. 'Feb-90') vorliegt.
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

type(loan_data['earliest_cr_line_date'][0])

pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date'].head(1)

# Berechnet die Zeitdifferenz zwischen dem 1. Dezember 2018 und dem Datum der frühesten Kreditlinie.
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2018-12-01') - loan_data['earliest_cr_line_date'])
/ np.timedelta64(1, 'D')) / 30.44)

# Zeigt deskriptive Statistiken für die Spalte 'mths_since_earliest_cr_line' an.
# Dies gibt uns einen Überblick über die Verteilung und mögliche Probleme (z.B. negative Werte).
loan_data['mths_since_earliest_cr_line'].describe()

# Der Kommentar besagt, dass Daten aus 1969 oder früher falsch konvertiert wurden
# (z.B. 1969 wurde zu 2069) und dadurch negative Differenzen berechnet wurden.
# Es gibt 2303 solche Werte, die das Problem belegen.
# Dieser Code filtert den DataFrame, um die Zeilen anzuzeigen, bei denen 'mths_since_earliest_cr_line' negativ ist.
# Dies hilft, die betroffenen Einträge zu identifizieren.
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line'] < 0].head()

# Es gibt 2303 solche Werte.
# Negative Werte werden durch den Maximalwert der Spalte ersetzt, da diese auf einer Fehlinterpretation des Jahres beruhen (z.B. '57' als 2057 anstatt 1957).
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

min(loan_data['mths_since_earliest_cr_line'])

"""Term"""

# Zeigt deskriptive Statistiken für die Spalte 'int_rate' an. Dies umfasst Kennzahlen wie Mittelwert, Standardabweichung, Min/Max-Werte und Quartile.
loan_data['int_rate'].describe()

# Zeigt die ersten Werte der Spalte 'term' an. Diese Spalte enthält die Laufzeit des Kredits in Monaten als String.
loan_data['term'].head(5)

# Zeigt deskriptive Statistiken für die Spalte 'term' an. Dies hilft, die Verteilung und die einzigartigen Werte zu verstehen.
loan_data['term'].describe()

# Erstellt eine neue Spalte 'term_int', indem der String ' months' aus der 'term'-Spalte entfernt wird, um nur die numerischen Werte zu erhalten.
loan_data['term_int'] = loan_data['term'].str.replace(' months', '')

# Zeigt die ersten 5 Werte der neuen Spalte 'term_int' an, um die Änderung zu überprüfen.
loan_data['term_int'].head(5)

# Überprüft den Datentyp der 'term_int'-Spalte und eines einzelnen Elements. Es wird erwartet, dass es sich noch um einen String handelt.
type(loan_data['term_int'])
type(loan_data['term_int'][25])

# Überprüft den Datentyp der 'term_int'-Spalte und eines einzelnen Elements. Es wird erwartet, dass es sich noch um einen String handelt.
loan_data['term_int'] = pd.to_numeric(loan_data['term'].str.replace(' months', ''))
loan_data['term_int'].head(5)

# Überprüft erneut den Datentyp eines Elements in 'term_int', um zu bestätigen, dass die Konvertierung erfolgreich war.
type(loan_data['term_int'][0])

"""Time since the loan was funded"""

loan_data['issue_d'].head(5)

# Annahme: Wir befinden uns im Dezember 2017
# Konvertiert die Spalte 'issue_d' (Ausgabedatum) in ein Datumsformat.
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

# Berechnet die Anzahl der Monate seit dem Ausgabedatum bis zum 01.12.2018.
# Hierfür wird die Differenz in Tagen berechnet und dann durch den durchschnittlichen Wert der Tage in einem Monat (30.44) geteilt.
loan_data['mths_since_issue_d'] = round(pd.to_numeric((pd.to_datetime('2018-12-01') - loan_data['issue_d_date']) / np.timedelta64(1, 'D')) / 30.44)

# Zeigt deskriptive Statistiken für die neu erstellte Spalte 'mths_since_issue_d' an.
loan_data['mths_since_issue_d'].describe()

"""# Data preparation: preprocessing discrete variables"""

# Zeigt eine Zusammenfassung des DataFrames 'loan_data' an, einschließlich Spaltennamen, Non-Null-Werten und Datentypen.
# Dies ist nützlich, um den aktuellen Zustand des DataFrames und die Ergebnisse der vorherigen Preprocessing-Schritte zu überprüfen.
loan_data.info()

# loan_data['grade_factor'] = loan_data['grade'].astype('category')

#grade
#sub_grade
#home_ownership
#verification_status
#loan_status
#purpose
#addr_state
#initial_list_status

# Erstellt Dummy-Variablen für die Spalte 'grade'.
# Jede eindeutige Kategorie in 'grade' wird zu einer neuen Spalte (z.B. 'grade:A', 'grade:B') mit Binärwerten (0 oder 1).
# 'prefix' und 'prefix_sep' werden verwendet, um die Namen der neuen Spalten prägnant zu gestalten.
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':')

# Erstellt Dummy-Variablen für mehrere kategoriale Spalten gleichzeitig und speichert sie in einer Liste.
# Diese Spalten sind: 'grade', 'sub_grade', 'home_ownership', 'verification_status', 'loan_status', 'purpose', 'addr_state', 'initial_list_status'.
# Jede get_dummies-Operation erstellt einen DataFrame mit den entsprechenden Binärvariablen.
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]
# Verkettet alle erstellten Dummy-DataFrames horizontal (axis = 1) zu einem einzigen DataFrame namens 'loan_data_dummies'.
# Dies kombiniert alle One-Hot-kodierten kategorialen Merkmale.
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

# Überprüft den Datentyp des 'loan_data_dummies' Objekts. Es sollte ein pandas DataFrame sein.
type(loan_data_dummies)

# Zeigt die Dimensionen (Anzahl der Zeilen und Spalten) des 'loan_data_dummies' DataFrames an.
# Dies hilft zu verstehen, wie viele neue Spalten durch die Dummy-Kodierung hinzugefügt wurden.
loan_data_dummies.shape

# Zeigt eine Zusammenfassung des 'loan_data_dummies' DataFrames an, einschließlich Spaltennamen und Datentypen.
# Dies bestätigt, dass die Dummy-Variablen als boolesche Typen oder Integer vorliegen.
loan_data_dummies.info()

# Fügt den DataFrame mit den neu erstellten Dummy-Variablen (loan_data_dummies) horizontal (axis = 1) an den ursprünglichen 'loan_data' DataFrame an.
# Dadurch werden die kategorialen Merkmale in eine für maschinelles Lernen geeignete Form gebracht.
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

# Zeigt alle Spaltennamen des aktualisierten 'loan_data' DataFrames an.
# Dies bestätigt, dass die neuen Dummy-Variablen-Spalten erfolgreich hinzugefügt wurden.
loan_data.columns.values

"""# Data preparation: check for missing values and clean"""

loan_data.isnull()

pd.options.display.max_rows = None
loan_data.isnull().sum()

pd.options.display.max_rows = 100

# loan_data$total_rev_hi_lim - There are 70276 missing values here.
# 'Total revolving high credit/credit limit', so it makes sense that the missing values are equal to funded_amnt.

# loan_data$acc_now_delinq
# loan_data$total_acc
# loan_data$pub_rec
# loan_data$open_acc
# loan_data$inq_last_6mths
# loan_data$delinq_2yrs
# loan_data$mths_since_earliest_cr_line
# - There are 29 missing values in all of these columns. They are likely the same observations.
# An eyeballing examination of the dataset confirms that.
# All of these are with loan_status 'Does not meet the credit policy. Status:Fully Paid'.
# We impute these values.

# loan_data$annual_inc
# - There are 4 missing values in all of these columns.

# loan_data$mths_since_last_record
# loan_data$mths_since_last_delinq

# 'Total revolving high credit/credit limit', so it makes sense that the missing values are equal to funded_amnt.
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace=True)

loan_data['mths_since_earliest_cr_line'].fillna(0, inplace=True)

loan_data['acc_now_delinq'].fillna(0, inplace=True)
loan_data['total_acc'].fillna(0, inplace=True)
loan_data['pub_rec'].fillna(0, inplace=True)
loan_data['open_acc'].fillna(0, inplace=True)
loan_data['inq_last_6mths'].fillna(0, inplace=True)
loan_data['delinq_2yrs'].fillna(0, inplace=True)
loan_data['emp_length_int'].fillna(0, inplace=True)

loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean(), inplace=True)

"""# PD model: Data preparation: Good/ Bad (DV for the PD model)"""

loan_data['loan_status'].unique()

loan_data['loan_status'].value_counts()

loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()

# Good/ Bad Definition
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default',
                                                       'Does not meet the credit policy. Status:Charged Off',
                                                       'Late (31-120 days)']), 0, 1)

#loan_data['good_bad'].sum()/loan_data['loan_status'].count()

loan_data['good_bad']

"""# PD model: Data Preparation: Splitting Data"""

# loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test

from sklearn.model_selection import train_test_split

# Here we don't split data into training and test
#train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

#loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

#loan_data_inputs_train.shape

#loan_data_targets_train.shape

#loan_data_inputs_test.shape

#loan_data_targets_test.shape

#loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)

#loan_data_inputs_train.shape

#loan_data_targets_train.shape

#loan_data_inputs_test.shape

#loan_data_targets_test.shape

"""# PD model: Data Preparation: Discrete Variables"""